sudo: required

services:
- docker

language: scala

scala:
- 2.12.6

env:
  global:
  - secure: RIapv4elK86C20isVh6iByb0CrcI28bi6Nw9yMgMfxOxyjS8wIguv13MzNnSzNNw8OyjBp0lNhFTIjccLZhFoNHq0yR5BycOmd+9+/lvLbRQUul7QIwyvW34cln9kIeEmKur6IN+BIcY/Oe78W45ORwxeVOheou9paVoaSUuQwqWJOv57RNlPcpsEOlddkUgrZDoouoEnPocWNhAGo9cdOyQDtguNxJTtWoxhF3vKNJD/BPo7m78rqpO42Behtf9DNZdg9zic5oUuwd4VGOw2m/q9GYJsq1vEqbgEqHWaFJeoSrsPRHOLWO2dIlRaAQx+B/LNJc6n3009PSlNyRQ5WtC6B4w95TtfvNDLW8pYRS1LDS4cHYVGlCdTL4hk4xhSCxp4FA9r0E0NmJsUcWebyUQ8DXXR1mF5wXt+yF33ne5AsP6OVJiZDv0QwZ0HxHhxxx78v7jy7BeTatYJfmz+tRD2q01zaluLjV/Aj9aARLQV8Z5YEKq1XW6NQ8YFZHxdEsTacNsf8VeTPRTCuG2sxU97ybyaup1bBzJt4IdIDTax7cMzNSXvgKCLJbtzHWEaF+Daw1ugsoiU7ZFz4GsvucD0Ajc70qqnXD7xyd/8h8a/QFIP+qDCUFxgVl0ZPbgsKCyUZ7R+I8l1QR7ht53YN9BOIOWxARwXEgbWaSruII=
  - secure: iVoWqu8uV/DZSUnP1ke7zuA9Rx9EMYGPG7EaOrTsCfCltazGJYNhfx04v+w1VixG4EaYkEWkQ4T7A9JuQHTZ6YUzBcpOOetRHJKlo3f0y1Twx4Q/qHDIql6wfqXO/kfm1FqZysS6m4YiL04pVWUf1MTA1NUkQU7T3PXv45I+lF9xkRyNARkrb3ZT12G1b5x76T2Eeo0WkneBjCR3u7VfW0YEFW8kXlnwa6H8JrR7EYxUmTA9Et4z67xpmHbFubwqfL5PkTTYwf3s0vdqI7wajTd1pBFWVZWDDGdNvWwA5UBdC6x+UzWV95ddgHi/TvNvJSW6sQ5If72zQpRiAqSC9nnxNhmx33iw/NhFfRbPkVQMrQLfFEAUxJkZXqoL2kk8ik0b+WmyrhAtt6LpJ50roZM7Rj/1ng1A+GkgtA9mHKPEOcT1HY+UC9FnLWb7WLhq8Kx9vSc2J7+Mn/0wUB+/RWoMvfvEqD7aYBfXMn4gHWZGMSSO96LUfxJ1UXki3iNzUv2IZnWJnmF67je1tWDovxkmhJluEBWWseW/3RdIgpayKmxAFqWoSzY8PXwTwzctUn2px1Il+uWp9CqbU4XUo+K4DEo6PvVpB2yEcwF3JGLVvcEi1FkMv01Mm0R5DUg9UE+v12T3DR1gDOkywgbQtysxRsMHqqpwmiH7LrppKSQ=

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin;
  sbt clean docker:publish;
